@WebServiceLayer_HostAddress = http://localhost:5001

GET {{WebServiceLayer_HostAddress}}/weatherforecast/
Accept: application/json

###

Get {{WebServiceLayer_HostAddress}}/api/movies
Accept: application/json
