@WebServiceLayer_HostAddress = http://localhost:5001

Get https://localhost:5001/api/users/person/tt0325710
Accept: application/json

-####
GET https://localhost:5001/api/movies/tt0325710
Accept:application/json

-###

GET https://localhost:5001/api/movies/tt0325710
Accept: application/json


